import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useState } from "react";

import Button from "@mui/material/Button";

import SnackBar from "../src/components/misc/SnackBar";
import AlertDialog from "../src/components/misc/AlertDialog";

export default function Home() {
  // ==== SNACKBAR STATES ===
  const [openSnackBar, setOpenSnackBar] = useState(false);
  const [snackBarMsg, setSnackBarMsg] = useState("");
  const [snackBarType, setSnackBarType] = useState(""); // "success", "warning", "error"
  const handleCloseSnackBar = () => {
    setOpenSnackBar(false);
  };

  const handleOpenSnackBar = () => {
    setOpenSnackBar(true);
  };

  // ==== CONFIRMATION DIALOG ====
  const [openDialog, setOpenDialog] = useState(false);
  const [action, setAction] = useState("");
  const [alertTitle, setAlertTitle] = useState("");
  const [alertMessage, setAlertMessage] = useState("");
  const handleCloseDialog = () => {
    setOpenDialog(false);
  };
  // ============================

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Button onClick={() => handleOpenSnackBar()}>Test Snackbar</Button>

        <SnackBar
          openSnackBar={openSnackBar}
          handleCloseSnackBar={handleCloseSnackBar}
          snackBarMsg={"HELLO"}
          snackBarType={"success"}
        />
        <AlertDialog
          openDialog={openDialog}
          closeDialog={handleCloseDialog}
          dialogAction={dialogAction}
          alertTitle={alertTitle}
          alertMessage={alertMessage}
        />
      </main>
    </div>
  );
}
